# Exercise:

1. Use PyTorch to confirm Xv = λv for the first eigenvector of X.

2. Confirm Xv = λv for the remaining eigenvectors of X (you can use NumPy or PyTorch, whichever you prefer).

In [1]:
import torch 

In [2]:
X = torch.tensor([[25, 2, 9.], [5, 26, -5.], [3, 7, -1.]])
X

tensor([[25.,  2.,  9.],
        [ 5., 26., -5.],
        [ 3.,  7., -1.]])

In [3]:
eigenvalues, eigenvectors = torch.linalg.eig(X)

In [4]:
eigenvalues

tensor([29.6762+0.j, 20.6212+0.j, -0.2974+0.j])

In [5]:
eigenvectors

tensor([[ 0.7118+0.j,  0.6502+0.j, -0.3422+0.j],
        [ 0.6665+0.j, -0.7446+0.j,  0.2379+0.j],
        [ 0.2217+0.j, -0.1509+0.j,  0.9090+0.j]])

### First pair of eigenvalue & eigenvector

In [6]:
eigenvalue_1 = eigenvalues[0].float()
eigenvalue_1

C:\Users\fajar\AppData\Local\Temp\ipykernel_17720\3460556336.py:1: UserWarning: Casting complex values to real discards the imaginary part (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\Copy.cpp:276.)
  eigenvalue_1 = eigenvalues[0].float()


tensor(29.6762)

In [7]:
eigenvector_1 = eigenvectors[:,0].float()
eigenvector_1

tensor([0.7118, 0.6665, 0.2217])

In [8]:
Xv1 = torch.matmul(X, eigenvector_1)
Xv1

tensor([21.1223, 19.7798,  6.5792])

In [9]:
λv1 = eigenvalue_1 * eigenvector_1
λv1

tensor([21.1223, 19.7798,  6.5792])

### Second pair of eigenvalue and eigenvector

In [10]:
eigenvalue_2 = eigenvalues[1].float()
eigenvalue_2

tensor(20.6212)

In [11]:
eigenvector_2 = eigenvectors[:,1].float()
eigenvector_2

tensor([ 0.6502, -0.7446, -0.1509])

In [12]:
Xv2 = torch.matmul(X, eigenvector_2)
Xv2

tensor([ 13.4077, -15.3554,  -3.1110])

In [13]:
λv2 = eigenvalue_2 * eigenvector_2
λv2

tensor([ 13.4077, -15.3554,  -3.1110])

### Third pair of eigenvalue and eigenvector

In [14]:
eigenvalue_3 = eigenvalues[2].float()
eigenvalue_3

tensor(-0.2974)

In [15]:
eigenvector_3 = eigenvectors[:,2].float()
eigenvector_3

tensor([-0.3422,  0.2379,  0.9090])

In [16]:
Xv3 = torch.matmul(X, eigenvector_3)
Xv3

tensor([ 0.1018, -0.0708, -0.2703])

In [17]:
λv3 = eigenvalue_3 * eigenvector_3
λv3

tensor([ 0.1018, -0.0708, -0.2703])

# Exercises:

1. Use PyTorch to decompose the matrix P (below) into its components V, Λ, and V**-1. Confirm that P = VΛV**-1.

2. Use PyTorch to decompose the symmetric matrix S (below) into its components Q, Λ, Q\**T. Confirm that S = QΛQ**T

Ans 1:

In [18]:
P = torch.tensor([[25, 2, -5], [3, -2, 1], [5, 7, 4.]])
P

tensor([[25.,  2., -5.],
        [ 3., -2.,  1.],
        [ 5.,  7.,  4.]])

In [19]:
S = torch.tensor([[25, 2, -5], [2, -2, 1], [-5, 1, 4.]])
S

tensor([[25.,  2., -5.],
        [ 2., -2.,  1.],
        [-5.,  1.,  4.]])

In [20]:
eigenvalues, eigenvectors = torch.linalg.eig(P)

In [21]:
eigenvalues

tensor([23.7644+0.j,  6.6684+0.j, -3.4328+0.j])

In [22]:
eigenvectors

tensor([[ 0.9511+0.j, -0.2386+0.j,  0.1626+0.j],
        [ 0.1218+0.j, -0.1924+0.j, -0.7705+0.j],
        [ 0.2837+0.j, -0.9519+0.j,  0.6163+0.j]])

In [24]:
Lambdas = torch.diag(eigenvalues).float()
Lambdas

tensor([[23.7644,  0.0000,  0.0000],
        [ 0.0000,  6.6684,  0.0000],
        [ 0.0000,  0.0000, -3.4328]])

In [25]:
V = eigenvectors.float()
V

tensor([[ 0.9511, -0.2386,  0.1626],
        [ 0.1218, -0.1924, -0.7705],
        [ 0.2837, -0.9519,  0.6163]])

In [26]:
Vinv = torch.linalg.inv(V)
Vinv

tensor([[ 1.1356,  0.0102, -0.2868],
        [ 0.3914, -0.7198, -1.0032],
        [ 0.0817, -1.1164,  0.2052]])

In [27]:
torch.matmul(V, torch.matmul(Lambdas, Vinv))

tensor([[25.0000,  2.0000, -5.0000],
        [ 3.0000, -2.0000,  1.0000],
        [ 5.0000,  7.0000,  4.0000]])

In [28]:
P

tensor([[25.,  2., -5.],
        [ 3., -2.,  1.],
        [ 5.,  7.,  4.]])

Ans 2:

In [30]:
eigenvalues, eigenvectors = torch.linalg.eig(S)
eigenvalues

tensor([26.2361+0.j,  3.2435+0.j, -2.4796+0.j])

In [31]:
eigenvectors

tensor([[ 0.9744+0.j,  0.1943+0.j, -0.1132+0.j],
        [ 0.0614+0.j,  0.2548+0.j,  0.9651+0.j],
        [-0.2163+0.j,  0.9473+0.j, -0.2363+0.j]])

In [32]:
Lambdas = torch.diag(eigenvalues).float()
Lambdas

tensor([[26.2361,  0.0000,  0.0000],
        [ 0.0000,  3.2435,  0.0000],
        [ 0.0000,  0.0000, -2.4796]])

In [34]:
Q = eigenvectors.float()
Q

tensor([[ 0.9744,  0.1943, -0.1132],
        [ 0.0614,  0.2548,  0.9651],
        [-0.2163,  0.9473, -0.2363]])

In [35]:
torch.matmul(Q, torch.matmul(Lambdas, Q.T))

tensor([[25.0000,  2.0000, -5.0000],
        [ 2.0000, -2.0000,  1.0000],
        [-5.0000,  1.0000,  4.0000]])

In [36]:
S

tensor([[25.,  2., -5.],
        [ 2., -2.,  1.],
        [-5.,  1.,  4.]])

Exercise: Using the matrix P from the preceding PyTorch exercises, demonstrate that these three SVD-eigendecomposition equations are true

In [38]:
P

tensor([[25.,  2., -5.],
        [ 3., -2.,  1.],
        [ 5.,  7.,  4.]])

In [37]:
U, d, VT = torch.linalg.svd(P)
d

tensor([26.1632,  8.1875,  2.5395])

In [39]:
U

tensor([[-0.9757,  0.1823,  0.1214],
        [-0.0975,  0.1350, -0.9860],
        [-0.1961, -0.9739, -0.1140]])

In [40]:
VT

tensor([[-0.9810, -0.1196,  0.1528],
        [ 0.0113, -0.8211, -0.5706],
        [-0.1937,  0.5581, -0.8069]])

In [41]:
D = torch.diag(d)
D

tensor([[26.1632,  0.0000,  0.0000],
        [ 0.0000,  8.1875,  0.0000],
        [ 0.0000,  0.0000,  2.5395]])

In [42]:
torch.matmul(U, torch.matmul(D, VT))

tensor([[25.0000,  2.0000, -5.0000],
        [ 3.0000, -2.0000,  1.0000],
        [ 5.0000,  7.0000,  4.0000]])

In [43]:
P

tensor([[25.,  2., -5.],
        [ 3., -2.,  1.],
        [ 5.,  7.,  4.]])

In [57]:
eigenvalues, eigenvectors = torch.linalg.eig(torch.matmul(P, P.T))
eigenvalues.float()

tensor([684.5149,  67.0359,   6.4492])

In [56]:
eigenvectors.float()

tensor([[-0.9757, -0.1823,  0.1214],
        [-0.0975, -0.1350, -0.9860],
        [-0.1961,  0.9739, -0.1140]])

In [59]:
# Left Singular Vector == eigenvectors of A(A**T)
U

tensor([[-0.9757,  0.1823,  0.1214],
        [-0.0975,  0.1350, -0.9860],
        [-0.1961, -0.9739, -0.1140]])

In [61]:
eigenvalues, eigenvectors = torch.linalg.eig(torch.matmul(P.T, P))
eigenvalues.float()

tensor([684.5149,   6.4492,  67.0359])

In [62]:
eigenvectors.float()

tensor([[ 0.9810,  0.1937, -0.0113],
        [ 0.1196, -0.5581,  0.8211],
        [-0.1528,  0.8069,  0.5706]])

In [73]:
# Right Singular Vector == eigenvector (A**T)A
VT.T
# as eigenvalues are arranged in order, so too are singular values
# by convention, arranged in descending order

# the differences are the order of the singular vectors and the minus sign for right singular vector

tensor([[-0.9810,  0.0113, -0.1937],
        [-0.1196, -0.8211,  0.5581],
        [ 0.1528, -0.5706, -0.8069]])

In [103]:
torch.column_stack((VT.T[:,0], VT.T[:,2], VT.T[:,1])) * -1
# swap column 2 and 1 to equal with the eigenvectors
# trying to multiply with negative 1 to equal the sign with eigenvectors

tensor([[ 0.9810,  0.1937, -0.0113],
        [ 0.1196, -0.5581,  0.8211],
        [-0.1528,  0.8069,  0.5706]])

In [97]:
eigenvectors.float()

tensor([[ 0.9810,  0.1937, -0.0113],
        [ 0.1196, -0.5581,  0.8211],
        [-0.1528,  0.8069,  0.5706]])

In [119]:
# Non Zero Singular Values of A
d

tensor([26.1632,  8.1875,  2.5395])

In [115]:
eigenvalues, eigenvectors = torch.linalg.eig(torch.matmul(P, P.T))
eigenvalues.float()

tensor([684.5149,  67.0359,   6.4492])

In [116]:
torch.sqrt(eigenvalues.float())

tensor([26.1632,  8.1875,  2.5395])

In [117]:
eigenvalues, eigenvectors = torch.linalg.eig(torch.matmul(P.T, P))
eigenvalues.float()

tensor([684.5149,   6.4492,  67.0359])

In [118]:
torch.sqrt(eigenvalues.float())
# difference in order in right singular value

tensor([26.1632,  2.5395,  8.1875])

Exercise:

Use the torch.svd() method to calculate the pseudoinverse of A_p, confirming that your result matches the output of torch.pinverse(A_p):

In [120]:
A_p = torch.tensor([[-1, 2], [3, -2], [5, 7.]])
A_p

tensor([[-1.,  2.],
        [ 3., -2.],
        [ 5.,  7.]])

In [121]:
torch.pinverse(A_p)

tensor([[-0.0877,  0.1777,  0.0758],
        [ 0.0766, -0.1193,  0.0869]])

In [122]:
U, d, VT = torch.linalg.svd(A_p)
d

tensor([8.6692, 4.1043])

In [123]:
U.float()

tensor([[ 0.1271,  0.4741,  0.8713],
        [ 0.0016, -0.8785,  0.4778],
        [ 0.9919, -0.0593, -0.1124]])

In [124]:
VT.float()

tensor([[ 0.5580,  0.8298],
        [-0.8298,  0.5580]])

In [125]:
D = torch.diag(d)
D

tensor([[8.6692, 0.0000],
        [0.0000, 4.1043]])

In [126]:
1/8.6692

0.115350897429982

In [127]:
1/4.1043

0.24364690690251686

In [128]:
torch.tensor([[0.1153, 0], [0, 0.2436]])

tensor([[0.1153, 0.0000],
        [0.0000, 0.2436]])

In [129]:
torch.inverse(D)

tensor([[0.1154, 0.0000],
        [0.0000, 0.2436]])

In [130]:
A_p

tensor([[-1.,  2.],
        [ 3., -2.],
        [ 5.,  7.]])

In [137]:
D_plus = torch.cat((torch.inverse(D), torch.tensor([[0,0]]).T), axis=1)
D_plus

tensor([[0.1154, 0.0000, 0.0000],
        [0.0000, 0.2436, 0.0000]])

In [138]:
torch.matmul(VT.T, torch.matmul(D_plus, U.T))

tensor([[-0.0877,  0.1777,  0.0758],
        [ 0.0766, -0.1193,  0.0869]])

In [139]:
torch.pinverse(A_p)

tensor([[-0.0877,  0.1777,  0.0758],
        [ 0.0766, -0.1193,  0.0869]])

Exercises:

With the matrix A_p provided below:

1. Uses the PyTorch trace method to calculate the trace of A_p
2. Use the PyTorch Frobenius norm method and trace method to demonstrate that ||A||_f = (Tr(A(A\**T))**1/2)

In [140]:
A_p

tensor([[-1.,  2.],
        [ 3., -2.],
        [ 5.,  7.]])

In [141]:
# Ans 1
torch.trace(A_p)

tensor(-3.)

In [142]:
torch.trace(torch.matmul(A_p, A_p.T))**(1/2)

tensor(9.5917)

In [143]:
torch.linalg.norm(A_p)

tensor(9.5917)

In [148]:
((-1)**2 + 2**2 + 3**2 + (-2)**2 + 5**2 + 7**2)**(1/2)

9.591663046625438