# Exercise:

1. Use PyTorch to confirm Xv = λv for the first eigenvector of X.

2. Confirm Xv = λv for the remaining eigenvectors of X (you can use NumPy or PyTorch, whichever you prefer).

In [1]:
import torch 

In [4]:
X = torch.tensor([[25, 2, 9.], [5, 26, -5.], [3, 7, -1.]])
X

tensor([[25.,  2.,  9.],
        [ 5., 26., -5.],
        [ 3.,  7., -1.]])

In [5]:
eigenvalues, eigenvectors = torch.linalg.eig(X)

In [6]:
eigenvalues

tensor([29.6762+0.j, 20.6212+0.j, -0.2974+0.j])

In [7]:
eigenvectors

tensor([[ 0.7118+0.j,  0.6502+0.j, -0.3422+0.j],
        [ 0.6665+0.j, -0.7446+0.j,  0.2379+0.j],
        [ 0.2217+0.j, -0.1509+0.j,  0.9090+0.j]])

### First pair of eigenvalue & eigenvector

In [16]:
eigenvalue_1 = eigenvalues[0].float()
eigenvalue_1

tensor(29.6762)

In [17]:
eigenvector_1 = eigenvectors[:,0].float()
eigenvector_1

tensor([0.7118, 0.6665, 0.2217])

In [21]:
Xv1 = torch.matmul(X, eigenvector_1)
Xv1

tensor([21.1223, 19.7798,  6.5792])

In [33]:
λv1 = eigenvalue_1 * eigenvector_1
λv1

tensor([21.1223, 19.7798,  6.5792])

### Second pair of eigenvalue and eigenvector

In [27]:
eigenvalue_2 = eigenvalues[1].float()
eigenvalue_2

tensor(20.6212)

In [28]:
eigenvector_2 = eigenvectors[:,1].float()
eigenvector_2

tensor([ 0.6502, -0.7446, -0.1509])

In [30]:
Xv2 = torch.matmul(X, eigenvector_2)
Xv2

tensor([ 13.4077, -15.3554,  -3.1110])

In [39]:
λv2 = eigenvalue_2 * eigenvector_2
λv2

tensor([ 13.4077, -15.3554,  -3.1110])

### Third pair of eigenvalue and eigenvector

In [36]:
eigenvalue_3 = eigenvalues[2].float()
eigenvalue_3

tensor(-0.2974)

In [37]:
eigenvector_3 = eigenvectors[:,2].float()
eigenvector_3

tensor([-0.3422,  0.2379,  0.9090])

In [38]:
Xv3 = torch.matmul(X, eigenvector_3)
Xv3

tensor([ 0.1018, -0.0708, -0.2703])

In [40]:
λv3 = eigenvalue_3 * eigenvector_3
λv3

tensor([ 0.1018, -0.0708, -0.2703])

# Exercises:

1. Use PyTorch to decompose the matrix P (below) into its components V, Λ, and V**-1. Confirm that P = VΛV**-1.

2. Use PyTorch to decompose the symmetric matrix S (below) into its components Q, Λ, Q\**T. Confirm that S = QΛQ**T

In [ ]:
P = torch.tensor([[25, 2, -5], [3, -2, 1], [5, 7, 4.]])
P

In [ ]:
S = torch.tensor([[25, 2, -5], [2, -2, 1], [-5, 1, 4.]])
S

Exercise: Using the matrix P from the preceding PyTorch exercises, demonstrate that these three SVD-eigendecomposition equations are true

Exercise:

Use the torch.svd() method to calculate the pseudoinverse of A_p, confirming that your result matches the output of torch.pinverse(A_p):